### PR TITLE
fix(client): create trace-token for outgoing requests when not in a request context

### LINKED ISSUE #203: Request interceptors error: No thread-bound request found
Hello,
I'm currently facing one issue which seems to be related to the RequestInterceptors used for tracing and logging of HTTP Requests.
Example:
[        RequestContextHolder.currentRequestAttributes()](https://github.com/SDA-SE/sda-spring-boot-commons/blob/3ab385c398340db74b0ad3394215ad4a29d1690c/sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java#L28)

Context: i'm using a thread pool to fetch & execute some tasks which call other REST services to manipulate data 

The error I have is the one fired from Spring RequestContextHolder.currentRequestAttributes() because the thread which execute the tasks does not have any request atttributes

image

Do you have any idea how this issue can be fixed ?

Kind Regards,
Dragos

### PR DESCRIPTION
**Pull request by JoergSiebahn**
fixes #203

### CODE REVIEW

File: sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java [hunk 1]
```diff
@@ -12,26 +12,33 @@
...
-            .getAttribute(TRACE_TOKEN_HEADER_NAME, RequestAttributes.SCOPE_REQUEST);
-
-    if (attribute instanceof String strAttribute) {
-      RequestContextHolder.currentRequestAttributes()
-          .setAttribute(TRACE_TOKEN_HEADER_NAME, strAttribute, RequestAttributes.SCOPE_REQUEST);
-      return strAttribute;
+            .setAttribute(TRACE_TOKEN_HEADER_NAME, strAttribute, RequestAttributes.SCOPE_REQUEST);
+        return strAttribute;
+      }
+    } catch (IllegalStateException e) {
```
Comment (christopher-cudennec) [inline sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java:40]: It's unfortunate that there is no clean way to find out if we're in a request context instead of catching the exception.

As alternative we could invoke `RequestContextHolder#getRequestAttributes` which would return `null` if the attributes are missing. Still it's an indirect way to find out and the implementation is slighty different because it does not fall back to `FacesRequestAttributesFactory` in case of JSF.

Comment (JoergSiebahn) [reply sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java:40]: Just from the wording, without knowing the actual implementation of the foreign library, _current_ sounds much more reasonable than _get_. What's so bad about catching a documented exception?

Comment (christopher-cudennec) [reply sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java:40]: Just that it should be an "exception" and not a regular use case :D 
But I'm fine with your approach since there is no better alternative like `hasRequestContext`.

**Review by christopher-cudennec — APPROVED** [review]

File: sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java (hunk 1 above)
Comment (JoergSiebahn) [reply sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java:40]: Well, first checking and then accessing can lead to edge cases. Maybe not for something that is bound to the current thread like here. But in many other cases, checking first and then accessing is not a good idea. Examples: Accessing existing or non-existing files after checking _exists_, modifying data in a non-transactional database after checking if it matches a specific criteria. There could always be another process modifying it at the same time.
